---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 3413290463-cAMTmSnYj9K34cwnmG2do6FfEr0F8KCwW5zCJGV
:access_token_secret: 3XB7kfpfWwhp705a11PXY1JejqmdOHnK1MWqHo249Izr2
